### ISSUE TITLE
Error generating index in Laravel 4.1 project

### ISSUE THREAD

**Issue by rodrigocruz** [m2mdas/phpcomplete-extended#17]
I get an error when trying to generate the index file:

---

Loading Index
Error detected while processing function phpcomplete_extended#readDataForProject..phpcomplete_extended#loadProject..<SNR>110_loadIndex..<SNR>110_readIndex:
line    2:
E605: Exception not caught: file /Users/rodrigocruz/Workspace/travesso-l41/.phpcomplete_extended/phpcomplete_index
Error detected while processing function phpcomplete_extended#readDataForProject..phpcomplete_extended#loadProject..<SNR>110_loadIndex:
line   43:
E171: Missing :endif
Error detected while processing function phpcomplete_extended#readDataForProject:
line    4:
E171: Missing :endif

---

This is the :PHPCompleteExtendedGenerateIndex result:

```
{"error":{"type":"ErrorException","message":"Undefined offset: 2","file":"\/Users\/rodrigocruz\/.vim\/bundle\/phpcomplete-extended\/bin\/IndexGenerator.php","line":902}}
```

**Comment by m2mdas** [comment]
Hello rodrigocruz,

The bug occurred while parsing [orphan @param doc-comment of Connection.php](https://github.com/laravel/framework/blob/master/src/Illuminate/Remote/Connection.php#L67). I fixed the bug. I also pushed some minor bug fixes. Please update `phpcomplete-extended` and `phpcomplete-extended-laravel` and run `:PHPCompleteExtendedGenerateIndex` command again.

Merry Christmas!!! Happy Holidays!! :)

**Comment by rodrigocruz** [comment]
Thanks for the fix, it worked :) 
I had another bug after that one, in line 480 of laravel.php. It complains that the var $fqcn doesn't exist, i added an isset temporarily and it works.

Thanks for the great plugin. Happy Holidays!

**Comment by m2mdas** [comment]
I fixed the bug also. Also pushed some minor bug-fixes today. Please update `phpcomplete-extended` and `phpcomplete-extended-laravel` installation. Don't hesitate to issue bug report. Will fix as soon as I can.

Happy Holidays!
