### ISSUE TITLE
I can't get this to work under vim on FreeBSD

### ISSUE THREAD

**Issue by jasin** [m2mdas/phpcomplete-extended#19]
I have installed composer.phar to /usr/local/bin/composer.phar 
I can run the composer.phar cmd from any directory on the system, permissions 755 root:wheel

but when I start up vim it ask me if I want to generate the index file, I say 'yes' and this is the outcome.

```
Error detected while processing function phpcomplete_extended#readDataForProject..phpcomplete_extended#loadProject..<SNR>26_loadInde
x..phpcomplete_extended#generateIndex:
line    2:
The composer command "/usr/local/bin/composer.phar" is not a valid Composer command. Please set g:phpcomplete_index_composer_command
 in your .vimrc file
Loading Index
Error detected while processing function phpcomplete_extended#readDataForProject..phpcomplete_extended#loadProject..<SNR>26_loadInde
x..<SNR>26_readIndex:
line    2:
Could not read index file .phpcomplete_extended/phpcomplete_index
Index Loaded.
```

any help on how to track down this problem would be much appreciated.
.vimrc contains these two lines

```
autocmd  FileType  php setlocal omnifunc=phpcomplete_extended#CompletePHP
let g:phpcomplete_index_composer_command="/usr/local/bin/composer.phar"
```

**Comment by jasin** [comment]
it should be noted, that i tried changing g:complete_index_composer_command in .vimrc to just "composer.phar" 
I tried putting composer.phar in base directory, i tried putting it in .vim/bundle/phpcomplete_extended dir and left the "php composer.phar" cmd as default and I still get the same error. 

I can not seem to tell phpcomplete_extended to use a valid composer cmd.

**Comment by m2mdas** [comment]
The plugin checks output of `/composer/command --version` to detect existence of composer. It seems that if `composer.phar` is more than months old it gives different output, which may be the problem. I pushed the fix. Please update plugin and run `:PHPCompleteExtendedGenerateIndex` command.

**Comment by jasin** [comment]
yes, that was the issue and one I fixed when I looked at the code and ran the cmd myself. ;) but thank you for fixing it upstream.
