### ISSUE TITLE
Generate Index Error

### ISSUE THREAD

**Issue by LukeMauldin** [m2mdas/phpcomplete-extended#21]
I recently installed phpcomplete-extended in VIM and I am trying to use it on a Laravel project.  I am getting the error below when attempting to generate the index.  I have included my .vimrc for reference.
The class 'Evolution\Tasking\TaskingServiceProvider'' referenced as not found is in my {app}/workbench/evolution/tasking directory.  The Laravel app loads the TaskingServiceProvider correctly.

.vimrc:
"Setup NeoBundle
if has('vim_starting')
   set nocompatible               " Be iMproved
   set runtimepath+=~/.vim/bundle/neobundle.vim/
 endif

 call neobundle#rc(expand('~/.vim/bundle/'))

 " Let NeoBundle manage NeoBundle
 NeoBundleFetch 'Shougo/neobundle.vim'

 " Popular NeoBundles
 NeoBundle 'Shougo/neosnippet.vim'
 NeoBundle 'Shougo/neosnippet-snippets'
 NeoBundle 'tpope/vim-fugitive'
 NeoBundle 'kien/ctrlp.vim'
 NeoBundle 'flazz/vim-colorschemes'

 " Required:
 filetype plugin indent on
 syntax on

" vimproc for PHP completion
NeoBundle 'Shougo/vimproc', {
      \ 'build' : {
      \     'windows' : 'make -f make_mingw32.mak',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'unix' : 'make -f make_unix.mak',
      \    },
     \ }
NeoBundle 'Shougo/unite.vim'
NeoBundle 'm2mdas/phpcomplete-extended'
NeoBundle 'm2mdas/phpcomplete-extended-laravel'

"Setup autocomplete function
let g:phpcomplete_index_composer_command="composer"
autocmd  FileType  php setlocal omnifunc=phpcomplete_extended#CompletePHP

 " If there are uninstalled bundles found on startup,
 " this will conveniently prompt you to install them.
 NeoBundleCheck

Result of running :PHPCompleteExtendedGenerateIndex
Generating autoload classmap
Generating index...
PHP Strict standards:  Declaration of RouterWrapper::resource() should be compatible with Illuminate\Routing\Router::resource($name, $controller, array $options = Array) i
n /Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php on line 382
PHP Stack trace:
PHP   1. {main}() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:0
PHP   2. IndexGenerator->addPlugin() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:54
PHP   3. include() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:247

Strict standards: Declaration of RouterWrapper::resource() should be compatible with Illuminate\Routing\Router::resource($name, $controller, array $options = Array) in /Us
ers/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php on line 382

Call Stack:
    0.0017     566904   1. {main}() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:0
    0.0093    1685696   2. IndexGenerator->addPlugin() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:54
    0.0097    1785848   3. include('/Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php') /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGe
nerator.php:247

PHP Fatal error:  Class 'Evolution\Tasking\TaskingServiceProvider' not found in /Users/lmauldin/dev/pe/apps/ngt/vendor/laravel/framework/src/Illuminate/Foundation/Provider
Repository.php on line 123
PHP Stack trace:
PHP   1. {main}() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:0
PHP   2. IndexGenerator->generateIndex() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:57
PHP   3. IndexGenerator->execHook() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:443
PHP   4. call_user_func_array() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:277
PHP   5. laravel->init() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:277
PHP   6. require_once() /Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php:136
PHP   7. require() /Users/lmauldin/dev/pe/apps/ngt/bootstrap/start.php:61
PHP   8. Illuminate\Foundation\ProviderRepository->load() /Users/lmauldin/dev/pe/apps/ngt/vendor/laravel/framework/src/Illuminate/Foundation/start.php:195
PHP   9. Illuminate\Foundation\ProviderRepository->compileManifest() /Users/lmauldin/dev/pe/apps/ngt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.
php:51
PHP  10. Illuminate\Foundation\ProviderRepository->createProvider() /Users/lmauldin/dev/pe/apps/ngt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.p
hp:89
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Evolution\Tasking\TaskingServiceProvider' not found","file":"\/Users\/lmau
ldin\/dev\/pe\/apps\/ngt\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":123}}{"error":{"type":"Symfony\Component\Debug\Excepti
on\FatalErrorException","message":"Class 'Evolution\Tasking\TaskingServiceProvider' not found","file":"\/Users\/lmauldin\/dev\/pe\/apps\/ngt\/vendor\/laravel\/framework
\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":123}}

**Comment by m2mdas** [comment]
From first glance it looks like an autoloading problem. Can you provide directory structure of `Evolution` namespace?

**Comment by LukeMauldin** [comment]
The folder structure is a bit complex.  I am working with a Laravel app (known as {app}) and in the composer.json it includes some packages with the Evolution namespace.  I also have several packages in the workbench directory that also contribute to parts of the Evolution namespace.  The TaskingServiceProvider is in one of the packages in the workbench directory.  Although it maybe an auto-loading problem, Laravel successfully loads the TaskingServiceProvider on app startup and unit tests run successfully against it. 

Folder structure:
{app}
    -app
    -bootstrap
    -vendor
        -evolution
            -core
                -src
                    -Evolution
                        -Core
                            -other files
    -workbench
        -tasking
           -composer.json
            -src
                -Evolution
                    -Tasking
                        -TaskingServiceProvider.php

composer.json autoload section for tasking package:
    "autoload": {
        "classmap": [
            "src/controllers",
            "src/migrations",
            "src/views",
            "tests"
        ],
        "psr-0": {
            "Evolution\Tasking\Tests": "tests/",
            "Evolution\Tasking\": "src/"
        }
    },

Beginning of file TaskingServiceProvider.php
<?php namespace Evolution\Tasking;

use Illuminate\Support\ServiceProvider;

class TaskingServiceProvider extends ServiceProvider {

**Comment by m2mdas** [comment]
Nevermind, I have recreated the problem. It seems that I have not autoloaded packages inside workbench directory before. I [pushed the fix](https://github.com/m2mdas/phpcomplete-extended-laravel/commit/7ee600e98685a0564a66dd6832c2ec2197d3ddf3). Please update `phpcomplete-extended-laravel` and run `:PHPCompleteExtendedGenerateIndex` command again.

**Comment by LukeMauldin** [comment]
That resolved this problem.  I will let you know if I experience additional problems.  Thank you.
