### ISSUE TITLE
error IndexGenerator.php

### ISSUE THREAD

**Issue by iwyg** [m2mdas/phpcomplete-extended#22]
I'm getting this error:

```
Undefined offset: 0 in /Users/malcolm/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php on line 41
```

Basically `$argv` is empty. Any idea?

**Comment by markwu** [comment]
me too. I have the same error.

**Comment by m2mdas** [comment]
Sorry for late reply, as I did not sit in front of my PC yesterday. 

It was a silly mistake from my part, I pushed the fix. Please update  `phpcomplete-extended` and run generate command again.

**Comment by markwu** [comment]
I confirmed it fixed.

**Comment by iwyg** [comment]
Yep, seems to work now. Thanks :+1:

**Comment by m2mdas** [comment]
Thanks! Closing this issue.
