### ISSUE TITLE
Auto completion failed when I use mutliple filetype

### ISSUE THREAD

**Issue by markwu** [m2mdas/phpcomplete-extended#23]
It is a weird bug I just found yesterday.

The auto completion only works when I use single file type like `set ft=php`, but not works when I use multiple file type like `set ft=php.html`.

**Comment by m2mdas** [comment]
Yes you are right. When you set multiple filetype on a file Vim calls `ftplugin/filetype.vim` for each file type. For PHP's case default `$VIMRUNTIME/ftplugin/php.vim` sets `omnifunc` to built in `phpcomplete#CompletePHP`. You can override it by creating `ftplugin/php.vim` in `~/.vim` folder and set `omnifunc` there. e.g in `~/.vim/ftplugin/php.vim`,

```
setlocal   omnifunc=phpcomplete_extended#CompletePHP
```

**Comment by m2mdas** [comment]
Actually the directory would be `~/.vim/after/ftplugin`.

**Comment by markwu** [comment]
I see, Thanks for the tips. This issue can be closed.
