### ISSUE TITLE
DBExt breaks phpcomplete-extended

### ISSUE THREAD

**Issue by jansenm** [m2mdas/phpcomplete-extended#25]
This is not a problem with phpcomplete-extended. I just put it here because it happens when you use phpcomplete-extended so you will seek the problem there.

Please leave open. I come back here when dbext fixes it (i notified them).

When both dbext and phpcomplete-extended are installed vim completely hangs for minutes when opening a php file. The following patch to dbext fixes that problem.

``` diff
diff --git a/autoload/dbext.vim b/autoload/dbext.vim
index b920cfb..f107b0d 100644
--- a/autoload/dbext.vim
+++ b/autoload/dbext.vim
@@ -1077,7 +1077,7 @@ function! s:DB_resetGlobalParameters()
         " Check for previous options for dbext and tell the user
         " the must update the parameters
         redir  @a
-        silent! exec 'let'
+        " silent! exec 'let'
         redir END

         if @a =~ 'db_ext'
```

**Comment by m2mdas** [comment]
Thanks for figuring out the issue.

**Comment by jansenm** [comment]
Cleanign up my issues. Not using this anymore and there is a release of dbext in 2015 with an commant sazing they fixed this. Closing this. Reopen if someone still has that issue. Guess not.
