### ISSUE TITLE
STDOUT of PHP is placed directly at the cursor position of the current buffer

### ISSUE THREAD

**Issue by mkraemer** [m2mdas/phpcomplete-extended#32]
Hi, 

when saving a file which contains syntax errors, the resulting STDOUT of php is just placed directly at the current cursor position of the buffer:
![screenshot](http://i.imgur.com/n3dMXta.png)

I'm not too sure this is a problem with phpcomplete-extended or maybe a general issue with my vim config, but i'd be very grateful if you could push me in the right direction here :)

thx

**Comment by lovek323** [comment]
No, I'm having the same issue.

**Comment by m2mdas** [comment]
Sorry for late reply. I haven't been able to give time lately. I will look into it this weekend. In the mean time can you isolate your environment with only `phpcomplete-*` and it's dependent plugins enabled using the procedure [listed here](https://github.com/junegunn/vader.vim#setting-up-isolated-testing-environment) and check that the bug can be regenerated?

**Comment by mkraemer** [comment]
Thank you for your reply :)

Yes, i can recreate the problem using the following .vimrc:

```
set nocompatible
filetype off

set rtp^=~/.vim/bundle/vimproc.vim
set rtp^=~/.vim/bundle/phpcomplete-extended
set rtp^=~/.vim/bundle/phpcomplete-extended-symfony

filetype plugin indent on
```

Again, thank you :)
Cheers

**Comment by m2mdas** [comment]
In before STDERR output was not redirected to `/dev/null` for background update index command. I assume you are using vim in terminal so error message was printed in the vim buffer. I did not catch the issue before because I use gVim and aliased it to redirect it's warning messages to `/dev/null`. Pushed a fix. Please update and check that it is working for you.

**Comment by mkraemer** [comment]
Awesome, the redirection of stderr fixes the problem, thank you :)

Unfortunately, the closing quote of the cmd-line was dropped in your commit:

```
let cmd .= ' 1>/dev/null 2>/dev/null
```

instead of 

```
let cmd .= ' 1>/dev/null 2>/dev/null'
```

Other than that, the issue is fixed, thank you :)

**Comment by m2mdas** [comment]
Ooops, sorry for silly mistake. Pushed the fix. Thank you :)

**Comment by m2mdas** [comment]
I should concentrate more. Even my commit message was wrong. Sorry again :)
