### ISSUE TITLE
Error: During saving

### ISSUE THREAD

**Issue by sducamp** [m2mdas/phpcomplete-extended#55]
I have this error during saving a PHP file : 
`Error detected while processing function phpcomplete_extended#checkUpdates..<SNR>52_updateLocalCache..<SNR>52_setClassData:
line    5:
E121: Undefined variable: g:phpcomplete_index`

**Comment by mkusher** [comment]
Hi @sducamp 
As I know @m2mdas doesn't maintain this plugin anymore. You can try my one https://github.com/mkusher/padawan.vim

**Comment by sducamp** [comment]
Thank you @mkusher I'm going to try yours!
