### ISSUE TITLE
Re-index project

### ISSUE THREAD

**Issue by manelet** [m2mdas/phpcomplete-extended#57]
How can I re-index or delete the index of a project?

My autocomplete is not working for the composer project, it suggest autocompletion for standard functions (like str_replace) but not for my classes inside my project, the indexing process printed some errors that should be fixed now, and I thought that re-indexing could be an option, how can I do that?

Thanks!

**Comment by mkusher** [comment]
I cat suggest you three options:
1. Remove `.phpcomplete_extended` folder from your project and restart vim
2. Run `:call phpcomplete_extended#generateIndex()` in vim
3. Try https://github.com/mkusher/padawan.vim

**Comment by manelet** [comment]
It works, thanks a lot.
