### ISSUE TITLE
Error processing 'plugin_name' vundle

### ISSUE THREAD

**Issue by alioukahere** [m2mdas/phpcomplete-extended#61]
I put these lines in my .vimrc file
`Bundle 'Shougo/unite.vim'`
`Bundle 'Shougo/vimproc.vim'`
`Bundle 'm2mdas/phpcomplete-extended'`
when I run the installation with **_:BundleInstall_**, I get errors _**Error processing 'plugin_name'**_ for all three bundle. And I don't understand. Help please !!!

**Comment by mkusher** [comment]
@Alioukahere maybe your .vim folder is not writable, check this issue https://github.com/VundleVim/Vundle.vim/issues/273
