### ISSUE TITLE
php executable not found! : Please help!

### ISSUE THREAD

**Issue by AnasR7** [m2mdas/phpcomplete-extended#65]
hey im newbie in vim..
i have some problem with install this plugin..
when i run vim, i got this popup massage

![image](https://cloud.githubusercontent.com/assets/23519166/25790416/8b918540-33e2-11e7-909a-6cc84abebca1.png)

best regards

sorry for my bad english
i'm new in github thanks...

**Comment by complex857** [comment]
Hi @IndieThink.

The error is complaining about the fact that vim just can't run `php` as a command line executable. You seem to be using windows (from the screenshot), so this might be a bit involved.
The end goal is that you should be able to run `cmd.exe` and if you type in `php -i` you get a phpinfo output.
First, you need to install, or find your installation of php on your system. Most likely you already have this one. You can do a file search for `php.exe`.
Once you got this one, you'll have to adjust your `$PATH` environment variable to include the directory that exe file lives in. You can modify these under your system settings:
![image](https://cloud.githubusercontent.com/assets/131617/25794489/6ca73d66-33d1-11e7-8bf0-e039fde6ee44.png)
Then find the button on the bottom saying environment variables somewhere here:
![image](https://cloud.githubusercontent.com/assets/131617/25794542/9f9a887c-33d1-11e7-84f4-87c7df3f629f.png)
And on the bottom part you see the PATH:
![image](https://cloud.githubusercontent.com/assets/131617/25794495/74154d90-33d1-11e7-82e6-744a739d0a07.png)
Click edit and add your directory (with a `;` added in front of it) to the end.

If everything went well, you can start `cmd.exe` and run `php -i` and it should work. After this the next time you start vim it should stop complaining about this error.

**Comment by IndieThink** [comment]
thanks i will try it!!

thankyou for fast reply! :)

**Comment by AnasR7** [comment]
thanks i will try it!!

thankyou for fast reply! :)

hahahaha take a easy buddy!!

im new in vim and this git

**Comment by AnasR7** [comment]
hi @complex857
i'm feels tired with this issues....
i follow your intstrution properly but no effect and still not install and  not working... :( 

i try in my envinronment variables...
![php_problem](https://cloud.githubusercontent.com/assets/23519166/25833521/2717a242-349c-11e7-9ceb-09e90c4a7902.png)

and i try in my terminal console pc
![php_problem2](https://cloud.githubusercontent.com/assets/23519166/25833557/603ae26e-349c-11e7-88b8-d0eabc7a0dc0.png)

and still not working :(

best regards

**Comment by complex857** [comment]
There seem to be some confusion here.

1. DON'T remove the rest of the PATH from the settings, you need those, you just need to **add at the end**.
2. The console you screenshoted seem to be a git bash shell, that's a bit different than the normal `cmd.exe`. I'm not 100% sure it will pick up your path changes from there. (see [this answer](https://superuser.com/questions/607533/windows-git-bash-bash-path-to-read-windows-path-system-variable))

So:
1. Restore your path settings, and keep the `C:\xampp\php` at the end. 
2. Reboot you machine (not sure if needed, but windows-es seem to like this)
3. Then Try hitting <kbd>windows</kbd>+<kbd>r</kbd> type in `cmd.exe` and check if `echo %PATH%` there will show what you've set up.
4. Check if vim itself still complains or not.

**Comment by AnasR7** [comment]
thank you somuch for your reply @complex857 .... :) 👍 

hahaha.. i see, i'm use git for my terminal command prompt to practice myself to use git i'm sorry for that...
because i'm still newbie here... HEHEHE

i will try it 
thank you somuch for your reply bro!

![26gsvam8upaczzxz2](https://cloud.githubusercontent.com/assets/23519166/25863473/356a8c0e-3516-11e7-9a07-5723c20f648d.gif)


best regards.
